services:
  - type: web
    name: SnapQuiz
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ACCESS_KEY
        sync: false
